In [1]:
import pandas as pd
import numpy as np
import sys
import pickle as pkl
import pickle
import joblib
import itertools
from math import ceil 

# Performance metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

#Classifier imports
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import  confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neural_network import MLPClassifier


In [4]:
# load  preprocessed dataset
data=pd.read_csv("Train.csv")

data_new=data.values

X=data_new[:,:-1] 
Y=data_new[:,-1]

#train-test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( X, Y, test_size=0.25,random_state=7)

In [5]:
#print the shape of training and test splits 
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(785336, 20)
(261779, 20)
(785336,)
(261779,)


In [6]:
#Centering data by mean i.e. subtracting mean from each data
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
joblib.dump(scaler, 'ss.pkl')
x_test=scaler.transform(x_test)

In [7]:
# Initialize our classifiers
mlp = MLPClassifier(solver='sgd')
knn = KNeighborsClassifier(n_neighbors=1)
bnb = BernoulliNB()
gnb = GaussianNB()
lr  = LogisticRegression(solver='newton-cg',class_weight='balanced',C=1.0)
lsvc = LinearSVC(class_weight='balanced',multi_class='crammer_singer')
lda = LinearDiscriminantAnalysis()
dtc= DecisionTreeClassifier(class_weight='balanced')
rfc= RandomForestClassifier(class_weight='balanced',n_estimators=200)


In [21]:
from time import time
t0 = time()
mlp.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_mlp = mlp.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_mlp)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_mlp))
pickle.dump(mlp, open("MLP.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_mlp)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 399.174 seconds
Accuracy : 96.22888008587395
Classification Report:-
               precision    recall  f1-score   support

         0.0       0.96      0.98      0.97    167247
         1.0       0.96      0.94      0.95     94532

    accuracy                           0.96    261779
   macro avg       0.96      0.96      0.96    261779
weighted avg       0.96      0.96      0.96    261779

Confusion matrix:
[[163377   3870]
 [  6002  88530]]

Total number of true positives(Attack identified as Attack)) 88530
Total number of false negatives (Attack identified as Benign) 6002
Total number of false positives(Benign identified as Attack) 3870
Total number of true negatives (Benign identified as Benign) 163377
Real positives: 94532
Real negatives: 167247
Predicted positives: 92400
Predicted negatives: 169379 



In [22]:
from time import time
t0 = time()
gnb.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_gnb = gnb.predict(x_test)
print("GaussianNB Accuracy :", accuracy_score(y_test, y_pred_gnb)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_gnb))
pickle.dump(gnb, open("GNB.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_gnb)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 0.387 seconds
GaussianNB Accuracy : 84.03653463417615
Classification Report:-
               precision    recall  f1-score   support

         0.0       0.84      0.93      0.88    167247
         1.0       0.85      0.68      0.75     94532

    accuracy                           0.84    261779
   macro avg       0.84      0.81      0.82    261779
weighted avg       0.84      0.84      0.84    261779

Confusion matrix:
[[155627  11620]
 [ 30169  64363]]

Total number of true positives(Attack identified as Attack)) 64363
Total number of false negatives (Attack identified as Benign) 30169
Total number of false positives(Benign identified as Attack) 11620
Total number of true negatives (Benign identified as Benign) 155627
Real positives: 94532
Real negatives: 167247
Predicted positives: 75983
Predicted negatives: 185796 



In [23]:
from time import time
t0 = time()
bnb.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_bnb = bnb.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_bnb)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_bnb))
pickle.dump(bnb, open("BNB.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_bnb)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 0.424 seconds
Accuracy : 80.09809801397361
Classification Report:-
               precision    recall  f1-score   support

         0.0       0.83      0.87      0.85    167247
         1.0       0.75      0.67      0.71     94532

    accuracy                           0.80    261779
   macro avg       0.79      0.77      0.78    261779
weighted avg       0.80      0.80      0.80    261779

Confusion matrix:
[[146053  21194]
 [ 30905  63627]]

Total number of true positives(Attack identified as Attack)) 63627
Total number of false negatives (Attack identified as Benign) 30905
Total number of false positives(Benign identified as Attack) 21194
Total number of true negatives (Benign identified as Benign) 146053
Real positives: 94532
Real negatives: 167247
Predicted positives: 84821
Predicted negatives: 176958 



In [29]:
from time import time
t0 = time()
knn.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_knn = knn.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_knn)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_knn))
pickle.dump(knn, open("KNN.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_knn)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 1362.382 seconds
Accuracy : 99.89189354379076
Classification Report:-
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    167247
         1.0       1.00      1.00      1.00     94532

    accuracy                           1.00    261779
   macro avg       1.00      1.00      1.00    261779
weighted avg       1.00      1.00      1.00    261779

Confusion matrix:
[[167080    167]
 [   116  94416]]

Total number of true positives(Attack identified as Attack)) 94416
Total number of false negatives (Attack identified as Benign) 116
Total number of false positives(Benign identified as Attack) 167
Total number of true negatives (Benign identified as Benign) 167080
Real positives: 94532
Real negatives: 167247
Predicted positives: 94583
Predicted negatives: 167196 



In [28]:
from time import time
t0 = time()
lr.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_lr = lr.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_lr)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_lr))
pickle.dump(lr, open("LR.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_lr)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 18.016 seconds
Accuracy : 93.43644830181184
Classification Report:-
               precision    recall  f1-score   support

         0.0       0.94      0.96      0.95    167247
         1.0       0.93      0.89      0.91     94532

    accuracy                           0.93    261779
   macro avg       0.93      0.92      0.93    261779
weighted avg       0.93      0.93      0.93    261779

Confusion matrix:
[[160894   6353]
 [ 10829  83703]]

Total number of true positives(Attack identified as Attack)) 83703
Total number of false negatives (Attack identified as Benign) 10829
Total number of false positives(Benign identified as Attack) 6353
Total number of true negatives (Benign identified as Benign) 160894
Real positives: 94532
Real negatives: 167247
Predicted positives: 90056
Predicted negatives: 171723 



In [27]:
from time import time
t0 = time()
lsvc.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_lsvc = lsvc.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_lsvc)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_lsvc))
pickle.dump(lsvc, open("LSVC.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_lsvc)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


E:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Model trained in 85.435 seconds
Accuracy : 93.18585524430914
Classification Report:-
               precision    recall  f1-score   support

         0.0       0.93      0.97      0.95    167247
         1.0       0.94      0.87      0.90     94532

    accuracy                           0.93    261779
   macro avg       0.93      0.92      0.92    261779
weighted avg       0.93      0.93      0.93    261779

Confusion matrix:
[[161568   5679]
 [ 12159  82373]]

Total number of true positives(Attack identified as Attack)) 82373
Total number of false negatives (Attack identified as Benign) 12159
Total number of false positives(Benign identified as Attack) 5679
Total number of true negatives (Benign identified as Benign) 161568
Real positives: 94532
Real negatives: 167247
Predicted positives: 88052
Predicted negatives: 173727 



In [26]:
from time import time
t0 = time()
lda.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_lda = lda.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_lda)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_lda))
pickle.dump(lda, open("LDA.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_lda)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 2.674 seconds
Accuracy : 87.42183292013492
Classification Report:-
               precision    recall  f1-score   support

         0.0       0.85      0.98      0.91    167247
         1.0       0.96      0.68      0.80     94532

    accuracy                           0.87    261779
   macro avg       0.90      0.83      0.85    261779
weighted avg       0.89      0.87      0.87    261779

Confusion matrix:
[[164287   2960]
 [ 29967  64565]]

Total number of true positives(Attack identified as Attack)) 64565
Total number of false negatives (Attack identified as Benign) 29967
Total number of false positives(Benign identified as Attack) 2960
Total number of true negatives (Benign identified as Benign) 164287
Real positives: 94532
Real negatives: 167247
Predicted positives: 67525
Predicted negatives: 194254 



In [25]:
from time import time
t0 = time()
dtc.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_dtc = dtc.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_dtc)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_dtc))
pickle.dump(dtc, open("DTC.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_dtc)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")


Model trained in 23.435 seconds
Accuracy : 99.92054366469426
Classification Report:-
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    167247
         1.0       1.00      1.00      1.00     94532

    accuracy                           1.00    261779
   macro avg       1.00      1.00      1.00    261779
weighted avg       1.00      1.00      1.00    261779

Confusion matrix:
[[167123    124]
 [    84  94448]]

Total number of true positives(Attack identified as Attack)) 94448
Total number of false negatives (Attack identified as Benign) 84
Total number of false positives(Benign identified as Attack) 124
Total number of true negatives (Benign identified as Benign) 167123
Real positives: 94532
Real negatives: 167247
Predicted positives: 94572
Predicted negatives: 167207 



In [24]:
from time import time
t0 = time()
rfc.fit(x_train,y_train)
tf = time() - t0
print ("Model trained in {} seconds".format(round(tf, 3)))

##### check on val data####
y_pred_rfc = rfc.predict(x_test)
print("Accuracy :", accuracy_score(y_test, y_pred_rfc)*100)
print("Classification Report:-\n",classification_report(y_test,y_pred_rfc))
pickle.dump(rfc, open("RFC.dat", "wb"))

# Compute confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,ShuffleSplit

cnf_matrix1 = confusion_matrix(y_test, y_pred_rfc)
print("Confusion matrix:")
print(cnf_matrix1)
tn = cnf_matrix1[0][0]
fp = cnf_matrix1[0][1]
fn = cnf_matrix1[1][0]
tp = cnf_matrix1[1][1]
print("\nTotal number of true positives(Attack identified as Attack))", tp)
print("Total number of false negatives (Attack identified as Benign)",fn)
print("Total number of false positives(Benign identified as Attack)",fp)
print("Total number of true negatives (Benign identified as Benign)",tn)

rp=tp+fn
rn=fp+tn
pp=tp+fp
pn=tn+fn

print("Real positives:",rp)
print("Real negatives:",rn)
print("Predicted positives:",pp)
print("Predicted negatives:",pn,"\n")



Model trained in 514.541 seconds
Accuracy : 99.93429572272795
Classification Report:-
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    167247
         1.0       1.00      1.00      1.00     94532

    accuracy                           1.00    261779
   macro avg       1.00      1.00      1.00    261779
weighted avg       1.00      1.00      1.00    261779

Confusion matrix:
[[167165     82]
 [    90  94442]]

Total number of true positives(Attack identified as Attack)) 94442
Total number of false negatives (Attack identified as Benign) 90
Total number of false positives(Benign identified as Attack) 82
Total number of true negatives (Benign identified as Benign) 167165
Real positives: 94532
Real negatives: 167247
Predicted positives: 94524
Predicted negatives: 167255 

